syntax = "proto3";

package all;

enum Mode {
  input = 0;
  output = 1;
  disabled = 2;
}

enum BankVoltage {
  V1P8 = 0;
  V3P3 = 1;
  V5P0 = 2;
}

enum PinPullState {
  None = 0;
  PullUp = 1;
  PullDown = 2;
}

message UsbBootloaderRequest {
  uint32 val = 1;
}

message Empty {
  uint32 status = 1;
}

message EchoMessage {
  string message = 1;
}

message GPIOReadRequest {
  uint32 gpio_pin = 1;
}

message PWMSetupRequest {
  uint32 gpio_pin = 1;
  uint32 wrap = 2;
  uint32 clock_div_int = 3;
  uint32 clock_div_frac = 4;
}

message PWMSetLevelRequest {
  uint32 gpio_pin = 1;
  uint32 level = 2;
}

message ADCReadRequest {
  uint32 gpio_pin = 1;
}

message ADCReadResponse {
  uint32 sample = 1;
}

message GPIOReadResponse {
  bool state = 1;
}

message GPIOWriteRequest {
  uint32 gpio_pin = 1;
  bool state = 2;
}

message SPISetupRequest {
  uint32 sclk_pin = 2;
  uint32 mosi_pin = 3;
  uint32 miso_pin = 4;
  uint32 instance_num = 5;
  uint32 baud_rate = 6;
}

message SPIWriteRequest {
  uint32 instance_num = 1;
  bytes data = 2;
  uint32 cs_pin = 3;
}

message SPIReadRequest {
  uint32 instance_num = 1;
  uint32 data = 2;
  uint32 cs_pin = 3;
  uint32 byte_count = 4;
}

message SPIReadResponse {
  bytes data = 1;
}

message GpioPinPullRequest {
  uint32 gpio_pin = 1;
  PinPullState state = 2;
}

message I2CSetupRequest {
  uint32 sda_pin = 1;
  uint32 scl_pin = 2;
  uint32 instance_num = 3;
}

message I2CWriteRequest {
  uint32 instance_num = 1;
  bytes data = 2;
  uint32 device_address = 3;
}

message I2CReadRequest {
  uint32 instance_num = 1;
  uint32 device_address = 2;
  uint32 byte_count = 3;
}

message I2CWriteThenReadRequest {
  uint32 instance_num = 1;
  bytes data = 2;
  uint32 device_address = 3;
  uint32 byte_count = 4;
}

message I2CWriteThenReadResponse {
  bytes data = 1;
}

message I2CReadResponse {
  bytes data = 1;
}

message GPIOModeRequest {
  uint32 gpio_pin = 1;
  Mode mode = 2;
}

message ErrorResponse {
  string message = 1;
}

message UartSetupRequest {
  uint32 baud_rate = 1;
  uint32 tx_pin = 2;
  uint32 rx_pin = 3;
  uint32 instance_num = 4;
}

message UartWriteRequest {
  bytes data = 1;
  uint32 timeout_ms = 2;
  uint32 instance_num = 3;
}

message UartReadRequest {
  uint32 byte_count = 1;
  uint32 timeout_ms = 2;
  uint32 instance_num = 3;
}

message UartReadResponse {
  bytes data = 1;
}

message FirmwareInfoRequest {
  uint32 info = 1;
}

message FirmwareInfoResponse {
  string hash = 1;
  string version = 2;
  string updated_at = 3;
}

message AppMessage {
  oneof kind {
    Empty emtpy = 2;
    ErrorResponse error_response = 10;

    GPIOModeRequest gpio_mode_request = 1;
    Empty gpio_mode_response = 42;

    GPIOWriteRequest gpio_write_request = 3;
    Empty gpio_write_response = 5;

    UsbBootloaderRequest usb_bootloader_request = 4;
    Empty usb_bootloader_response = 9;

    GPIOReadRequest gpio_read_request = 6;
    GPIOReadResponse gpio_read_response = 7;

    I2CSetupRequest i2c_setup_request = 11;
    Empty i2c_setup_response = 12;

    I2CWriteRequest i2c_write_request = 13;
    Empty i2c_write_response = 14;

    I2CReadRequest i2c_read_request = 15;
    I2CReadResponse i2c_read_response = 16;

    SPISetupRequest spi_setup_request = 17;
    Empty spi_setup_response = 18;

    SPIReadRequest spi_read_request = 19;
    SPIReadResponse spi_read_response = 20;

    SPIWriteRequest spi_write_request = 21;
    Empty spi_write_response = 22;

    FirmwareInfoRequest firmware_info_request = 36;
    FirmwareInfoResponse firmware_info_response = 37;

    UartSetupRequest uart_setup_request = 49;
    Empty uart_setup_response = 50;

    UartReadRequest uart_read_request = 51;
    UartReadResponse uart_read_response = 52;

    UartWriteRequest uart_write_request = 53;
    Empty uart_write_response = 54;

    GpioPinPullRequest gpio_pin_pull_request = 55;
    Empty gpio_pin_pull_response = 56;

    ADCReadRequest adc_read_request = 57;
    ADCReadResponse adc_read_response = 58;

    I2CWriteThenReadRequest i2c_write_then_read_request = 59;
    I2CWriteThenReadResponse i2c_write_then_read_response = 60;

    PWMSetupRequest pwm_setup_request = 61;
    Empty pwm_setup_response = 62;

    PWMSetLevelRequest pwm_set_level_request = 63;
    Empty pwm_set_level_response = 64;
  }
}